version: 2
updates:
  # Maintain Maven dependencies
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"

  # Maintain Yarn dependencies
  - package-ecosystem: "npm"
    directory: "/war"
    schedule:
        interval: "weekly"
        day: "sunday"

  # Maintain GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
